README.md
=> bypass execution policy

.vscode/settings.json, examples/client_example.py, examples/client_example.ts, examples/server.rs, python-sdk/desktop_use/client.py, python-sdk/desktop_use/models.py
=> fix: calculator examples not working

README.md, mcp/README.md, src/platforms/macos.rs
=> Add MacOS support & fix build issues & update docs

Cargo.lock, examples/mspaint.py, examples/terminator-rust-examples/server/src/main.rs, python-sdk/desktop_use/client.py, terminator/Cargo.toml, terminator/src/element.rs, terminator/src/platforms/macos.rs, terminator/src/platforms/windows.rs, ts-sdk/src/index.ts
https://github.com/user-attachments/assets/7dec0163-fd20-4e83-8750-7c658126fa7b
=> Add mouse drag and  mspaint.py

python-sdk/desktop_use/models.py, terminator/src/platforms/windows.rs, terminator/src/selector.rs, ts-sdk/src/index.ts
@louis030195 
can you please release this version of server and ts-sdk
=> feat: add ClassName selector and is_keyboard_focusable attribute

examples/snipping_tool.py, examples/terminator-rust-examples/server/src/main.rs, python-sdk/desktop_use/client.py, python-sdk/desktop_use/models.py, terminator/src/element.rs, terminator/src/platforms/windows.rs, ts-sdk/src/index.ts
https://github.com/user-attachments/assets/cf1346bc-dedf-4ca2-82fd-2fd5599d8bc5
=> feat: add mouse control methods and snipping tool example

README.md
- document benchmark test location
- highlight benchmark performance
- `cargo test --workspace --quiet` *(fails: failed to clone uni-ocr dependency)*
=> Update README with benchmark info

Cargo.lock, Cargo.toml, workflow-recorder/Cargo.toml, workflow-recorder/README.md, workflow-recorder/examples/record_workflow.rs, workflow-recorder/src/error.rs, workflow-recorder/src/events.rs, workflow-recorder/src/intent.rs, workflow-recorder/src/lib.rs, workflow-recorder/src/recorder.rs, workflow-recorder/src/recorder/windows.rs
Implements #17: Basic workflow recording crate
- Records UI events on Windows (mouse, keyboard, window focus)
- Captures UI element information via Windows UI Automation
- Outputs recordings as JSON
- Cross-platform architecture (Windows-only implementation)
- Example with Ctrl+C termination
/claim #17
=> feat: Basic workflow recording crate

terminator/src/selector.rs
@louis030195 , Its important to keep this part else all the examples stopped working due to this
=> fix custom role not working

bindings/python/Cargo.toml, bindings/python/src/bin/stub_gen.rs, bindings/python/terminator.pyi
=> feat(stub-gen): Add async function type fixing to stub generator

terminator/src/platforms/macos.rs, terminator/src/platforms/windows.rs, terminator/src/selector.rs
use this tool to get `AutomatinID` on windows, 
https://github.com/FlaUI/FlaUInspect
automation id is more like a id of html!!
=> feat: windows automation id support

terminator/src/platforms/windows.rs
=> fix: build :(

bindings/nodejs/index.d.ts, bindings/nodejs/src/desktop.rs, bindings/python/src/desktop.rs, bindings/python/terminator.pyi, terminator/src/lib.rs, terminator/src/platforms/linux.rs, terminator/src/platforms/macos.rs, terminator/src/platforms/mod.rs, terminator/src/platforms/windows.rs
https://discord.com/channels/1016600064807940126/1362794779766947941
=> feat: get_active_monitor_name

examples/gmail_automation.py, terminator/src/platforms/windows.rs
feat: Add Gmail automation example using Terminator SDK
/claim #24
Implements a script to automate Gmail operations including:
- Opening compose window
- Filling recipient, subject, and body
- Sending email and verifying in sent folder
https://github.com/user-attachments/assets/dcacef2d-07f5-44a4-af9e-606d997ef092
=> feat: Add Gmail automation example using Terminator SDK

terminator/src/selector.rs
=> fix: reorder selector match patterns to prioritize specific over generic

.vscode/launch.json, examples/server.openapi.json, examples/terminator-rust-examples/server/src/main.rs, mcp/package-lock.json, mcp/package.json, mcp/src/index.ts, mcp/src/terminator.ts, swagger.html, terminator/examples/list_processes_and_windows.rs, terminator/examples/print_accessibility_tree.rs, terminator/src/element.rs, terminator/src/lib.rs, terminator/src/locator.rs, terminator/src/platforms/macos.rs
_⚠️ I need to clean this PR up (e.g. multiple smaller PRs, remove debugging code, etc) but it may take me a day or so before I have time. So wanted to push this up for review and feedback now._
- [WIP still not great] #67  Add initial OpenAPI spec manually generated (by AI/LLM) from the server code
=> Improve MacOS support and more features!

examples/gnome-calculator.py, terminator/Cargo.toml, terminator/src/platforms/linux.rs, terminator/src/platforms/mod.rs, terminator/src/selector.rs
=> feat: add support for linux

examples/gnome-calculator.py
https://github.com/user-attachments/assets/b763802e-96be-4133-afcb-2156e7ad0862
=> fix gnome-calculator.py to work on wayland

terminator-mcp-agent/README.md, terminator-mcp-agent/install.ps1
need to test it,
@louis030195 can you release an artifact of mcp binary by merging this #97!!
=> one liner mcp setup for windows

terminator/src/platforms/windows.rs, terminator/tests/open_app.rs
fix: #94 
related: #102
```bash
cargo test --test open_app
```
sorry for the delay, i was [pretty cooked](https://stackoverflow.com/questions/79663939/launch-application-using-app-id-and-get-pid-in-return-on-windows?noredirect=1#comment140512197_79663939)
=> fix: opening applications

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/publish-mcp.yml, scripts/install_linux_deps.sh, terminator/src/platforms/linux.rs
Ref: https://github.com/mediar-ai/terminator/actions/runs/15784039664/job/44496382227
=> add dockerfile and fix publish-mcp.yml

.github/workflows/ci-wheels.yml, .github/workflows/publish-npm.yml, bindings/nodejs/npm/win32-arm64-msvc/README.md, bindings/nodejs/npm/win32-arm64-msvc/package.json, bindings/nodejs/package.json
--> python wheel
https://github.com/divanshu-go/terminator/actions/runs/15798236497/workflow?pr=6
--> npm
https://github.com/divanshu-go/terminator/actions/runs/15798524498?pr=6
closes #131 
closes #56
=> feat: release npm package and python wheels for Windows ARM64

terminator/src/platforms/linux.rs
https://github.com/user-attachments/assets/26ed453b-9827-4366-ad52-41ef659fc3d4
=> fix(linux): improve open_application with better PID fallback and D-Bus resolution

examples/gnome-calculator.py, terminator/src/platforms/linux.rs
https://github.com/user-attachments/assets/ed5273a4-64bf-41f8-835b-8b90a9e9971a
=> fix(linux): fallback to manual traversal if CollectionProxy is unavailable

examples/python_mcp_chunk_stream.py, examples/python_mcp_stream_progress.py, terminator-mcp-agent/src/server.rs
This PR enhances the `execute_sequence` tool to provide detailed, step-by-step execution information, simulating a streaming experience for clients. The response now includes:
- An **execution plan** outlining all steps.
- **Detailed step results** with progress indicators, timing, and status for each executed tool.
- A comprehensive **execution summary** with overall statistics.
A new Python example (`examples/python_mcp_chunk_stream.py`) demonstrates how to consume and display this structured output.
- …
=> Implement chunk streaming for execute sequence

bindings/nodejs/index.d.ts, bindings/nodejs/package-lock.json, bindings/nodejs/src/element.rs, bindings/python/src/element.rs, bindings/python/terminator.pyi, examples/mspaint.py, examples/notepad.py, examples/snipping_tool.py, examples/vlc_auto_player.py, terminator-workflow-recorder/tests/text_input_tracker_test.rs, terminator/src/element.rs, terminator/src/platforms/linux.rs, terminator/src/platforms/macos.rs, terminator/src/platforms/windows.rs
https://github.com/user-attachments/assets/0059c32f-e844-47f0-8022-30c2f0f6dccf
=> fix examples and win32 app launching

terminator/src/platforms/windows.rs
```
Simplified the clipboard text input logic by removing the `catch_unwind` mechanism. The code now directly attempts clipboard input and falls back to key-by-key if an error is returned. The log level for the fallback message has been adjusted from `warn!` to `debug!` to reflect that these errors do not always indicate a functional failure.
The `catch_unwind` block was removed to simplify the code, as the user reported that clipboard typing often …
```
=> Remove catch_unwind from clipboard typing

terminator-mcp-agent/src/helpers.rs, terminator-mcp-agent/src/server.rs, terminator-mcp-agent/src/utils.rs
Introduces a fallback selector mechanism for element identification. If the primary selector and any parallel alternative selectors fail, a list of fallback selectors will be tried sequentially. This enhances robustness by providing additional strategies for locating elements, and all attempted selectors are now included in error responses.
This feature provides a more resilient way to locate UI elements, improving the agent's ability to interact with …
=> Implement fallback selector in server and utils

terminator-mcp-agent/README.md
Adds comprehensive documentation for the `execute_sequence` tool, including a fully-annotated, generic sample workflow (Windows Calculator) and explanations of its key components, templating, and best practices. This addresses the need for a detailed, shareable reference without exposing private workflow data.
The added documentation is located in `terminator-mcp-agent/README.md` under a new section "📚 Full `execute_sequence` Reference & Sample …
=> Add documentation for execute sequence tool

terminator-mcp-agent/src/helpers.rs
This PR enhances variable substitution to allow for expression evaluation within `{{...}}` placeholders. This enables dynamic boolean logic (e.g., `contains()`, `startsWith()`, `==`) directly within configuration values, which can then be used by tools expecting boolean inputs.
This change allows for more flexible configuration, for example:
```json
{
"state": "{{contains(product_types, 'FEX')}}"
}
```
The `product_types` variable would be evaluated, …
=> Create functions for variable subscription

.cursor/rules/terminator-development-guide.mdc
Adds a new section to the `terminator-development-guide.mdc` outlining best practices for using the `format!` macro, focusing on efficiency, readability, and adherence to `cargo clippy` guidelines.
N/A
This update aims to ensure our codebase consistently meets `cargo clippy -- -D warnings` standards and minimizes unnecessary string allocations.
=> Add format function instruction for clippy compliance

terminator-cli/src/main.rs
Implements client-side validation for `required` variables in MCP workflow definitions. This ensures that all `required` variables (defaulting to true) either have a `default` value or are explicitly provided in the workflow's `inputs`. This provides early feedback during local development, complementing server-side checks.
This PR introduces a new validation step in the `terminator-cli` to catch missing required workflow variables before deployment, …
=> Implement required workflow variable property

examples/README.md
```
Adds a `README.md` file to the `examples/` directory. This README contains a concise markdown table that lists all available examples, their respective paths, and a brief description for each, improving discoverability and providing a quick overview of the project's examples.
As per the user's request, this `README.md` *only* contains the example table and no other content.
```
=> Create examples README table

terminator/src/platforms/windows.rs
Adds a robust fallback mechanism to the Windows `close()` function. If UI Automation's `WindowPattern` and `Alt+F4` fail, the system now attempts to forcibly close the application using `taskkill` or `powershell Stop-Process` based on its Process ID (PID).
This change enhances the reliability of closing Windows applications by introducing a multi-stage fallback:
1.  Attempts to use the `WindowPattern` close method.
2.  If that fails, sends `Alt+F4`.
3. …
=> Add terminal close fallback

terminator/src/platforms/windows/engine.rs, terminator/src/platforms/windows/utils.rs, terminator/tests/path_test.rs
use this ui inspector to get element's path https://github.com/dualbios/kDg.FlaUInspect
```bash
cargo test --test path_test -- --nocapture
```
=> feat: path selector
