- examples/win_automation.rs
- src/platforms/windows.rs
`start` command isn't able to open uwp applications, so it'd be better if we use app id.
> fix: opening uwp application

- mcp/README.md
The nested code blocks for bash and powershell are using triple backticks inside the main code block, which won't render correctly.
**fix**
> fix the error formatting in Readme

- examples/vlc_auto_player.py
- terminator/src/selector.rs
Add VLC media player automation example script with support for YouTube streams and local video playback
- Provides command-line options for playing YouTube/network streams or local video files
- Demonstrates automated playback, play/pause, and robust UI interaction
- Includes usage instructions for both modes at the top of the script
https://github.com/user-attachments/assets/32719e83-7359-4ec2-8d7d-1330b666bd22
https://github.com/user-attachments/assets/3ea44729-cdbc-49f8-9bf7-831e52f4862f
> Add VLC media player automation example

- .github/workflows/ci.yml
- add `ci.yml` workflow to compile the Rust workspace on Mac and Windows
- `cargo check` *(fails: failed to clone git dependency)*
- `cargo fmt --all -- --check` *(fails: `cargo-fmt` is not installed)*
> Add CI build workflow

- bindings/nodejs/src/desktop.rs
- bindings/python/src/desktop.rs
- examples/terminator-rust-examples/server/src/main.rs
- examples/terminator-rust-examples/win_automation/src/main.rs
- terminator/benches/element_tree_benchmarks.rs
- terminator/benches/tree_performance_benchmarks.rs
- terminator/examples/advanced_window_targeting.rs
- terminator/examples/benchmark_example.rs
- terminator/examples/list_processes_and_windows.rs
- terminator/examples/serialize_deserialize_element.rs
- terminator/examples/serialize_element.rs
- terminator/examples/simple_process_list.rs
- terminator/examples/smart_deserialize.rs
- terminator/examples/uielement_deserialize.rs
- terminator/src/element.rs
- terminator/src/lib.rs
- terminator/src/tests/e2e_tests.rs
- terminator/src/tests/firefox_window_tests.rs
@louis030195 the create_engine function is already sync , so therefore there is no need for Desktop::new() to be async.
using async , adds overhead to it , likely some milliseconds
> remove async from Desktop::new

- bindings/nodejs/index.d.ts
- bindings/nodejs/src/element.rs
- bindings/python/src/element.rs
- examples/monitor_example.py
@louis030195 I tested it on the vagrant box , it also has multi montor feature using virtual box settings
```bash
C:\Users\vagrant\terminator>python examples\monitor_example.py
Found window 1: Administrator: C:\Windows\system32\conhost.exe - python  examples\monitor_example.py
Monitor information:
Name: Unknown Monitor 65537
ID: monitor_0
Position: (0, 0)
----------
Found window 2: monitor on 1.txt - Notepad
Monitor information:
Name: Unknown Monitor 65537
ID: monitor_0
Position: (0, 0)
----------
Found window 3: monitor on 2.txt - Notepad
Monitor information:
Name: Unknown Monitor 65539
ID: monitor_1
Position: (955, 0)
----------
Found window 4: monitor on 3.txt - Notepad
Monitor information:
Name: Unknown Monitor 65541
ID: monitor_2
Position: (1910, 0)
---------- …
```
> add example for .monitor()

- README.md
Use `pip install terminator.py` in docs instead of `terminator-py`, to align with naming conventions similar to `terminator.js` on NPM. Note that pip treats `-`, `_`, and `.` as equivalent per PEP 503, so all variants are valid.
> docs(readme): clarify pip install behavior with normalized package names

- .gitignore
- examples/mspaint.py
- examples/notepad.py
- examples/snipping_tool.py
- scripts/gui-launch.ps1
- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/install-openssh.ps1
- **Automated VM Setup**: Windows 10 environment with 4GB RAM and 2 CPU cores
- **GUI Application Management**: `gui-launch` script for running GUI apps in non-interactive sessions
- **Remote Development Support**: 
- SSH access (port 2222)
- RDP connection support
- VS Code/Cursor Remote SSH integration
- **Pre-installed Tools**:
- Git
- Python
- PSTools
- Scoop package manager
The setup is particularly useful for development scenarios where you want to:
- Keep your development environment isolated
- Avoid GUI interruptions during coding sessions
- Use remote development tools while maintaining access to Windows-specific features
1. Run `vagrant up` to create the VM
2. Connect using either:
- `vagrant ssh` for SSH access
- `vagrant rdp` for RDP access
3. Test the `gui-launch` function …
> feat: Add Windows 10 VM setup with GUI application management

- terminator/src/platforms/windows.rs
- terminator/src/tests/get_applications_tests.rs
- terminator/src/tests/mod.rs
related: #21
some apps doesn't renders `Window` control type, some of them are using `Pane`, 
as an example claude and the discord app:
> fix: getting all application

- terminator/src/platforms/linux.rs
- terminator/src/platforms/macos.rs
- terminator/src/platforms/windows.rs
```
Resolves `non-exhaustive patterns` compilation errors by adding `Selector::Invalid` match arms to macOS and Linux platform implementations. This ensures all `Selector` enum variants are handled, returning `AutomationError::InvalidArgument` for invalid selectors.
- For macOS (`terminator/src/platforms/macos.rs`), `find_elements` and `find_element` now handle `Selector::Invalid` by returning `AutomationError::InvalidArgument`.
- For Linux …
```
> Fix non-exhaustive pattern matching

- terminator-mcp-agent/src/server.rs
- terminator-mcp-agent/src/utils.rs
Adds a new `set_value` tool to the MCP agent, enabling direct modification of an element's text value using the underlying accessibility API. This provides a more robust and faster alternative to simulated typing for input fields.
This PR introduces the `set_value` tool, which allows setting the value of editable UI elements (like textboxes) directly.
*   A new `SetValueArgs` struct defines the tool's parameters, including `selector`, `value`, and …
> Implement set_value tool in MCP hat

- terminator-mcp-agent/tests/execute_sequence_benchmark.rs
Adds an ignored integration test to benchmark the `execute_sequence` function's wall-clock performance against a real website. The test launches the MCP agent, executes a simple navigation and wait workflow, and compares client-side elapsed time with the agent's reported duration.
This benchmark provides a reproducible performance snapshot of `execute_sequence` in a real-world browsing scenario.
To run: `cargo test -- --ignored` (requires a graphical …
> Create speed benchmark for execute_sequence

- Cargo.lock
- terminator-mcp-agent/Cargo.toml
- terminator-mcp-agent/src/bin/gist_executor.rs
This PR enhances the `gist_executor` to support parsing workflow definitions from both JSON and YAML formats. It automatically detects and deserializes content, including direct `ExecuteSequenceArgs` and wrapped tool-call structures.
The `gist_executor` now transparently handles workflows provided in either JSON or YAML (including wrapped tool-call formats); it automatically selects the correct parser without additional user flags. This improves …
> Enable gist executor to read yaml

- terminator-mcp-agent/README.md
- terminator-mcp-agent/src/helpers.rs
```
This PR introduces support for GitHub Actions-style variable syntax (`${{...}}`) in MCP workflows, alongside the existing `{{...}}` syntax for backward compatibility. This change aims to make variable substitution more intuitive for users familiar with GitHub Actions.
The `terminator-mcp-agent/README.md` has been updated to reflect the new syntax in examples and the templating section. New unit tests were added in …
```
> Update variable substitution to github action style

- Cargo.lock
- terminator-cli/Cargo.toml
- terminator-cli/src/main.rs
Introduces a new `terminator run` command to the CLI, enabling direct execution of YAML/JSON workflows. This allows users to run workflows defined in local files, GitHub Gists, or raw URLs, streamlining the workflow execution process within the `terminator` ecosystem.
- The direct `terminator-mcp-agent` dependency was removed from `terminator-cli`'s `Cargo.toml` to reduce compilation overhead. The CLI now defaults to spawning `npx -y …
> Integrate gist executor into terminator cli

- terminator/src/element.rs
- terminator/src/platforms/linux.rs
- terminator/src/platforms/macos.rs
- terminator/src/platforms/windows.rs
```
Exposes the `is_toggled` property in the serialized UI tree, allowing clients to understand the toggle state of UI elements. This property is fully implemented and populated for Windows elements when available. For macOS and Linux, `is_toggled` is included in `UIElementAttributes` but defaults to `None`, ensuring cross-platform compatibility.
This change enhances the fidelity of the serialized UI tree by providing more detailed state information …
```
> Expose properties to serialized ui tree

- .github/workflows/ci.yml
Fixes CI smoke test failures caused by telemetry initialization blocking server startup.
The telemetry retry logic (15-30 minutes) was blocking the MCP server from starting in CI environments where no OpenTelemetry collector is available. This caused health check timeouts and smoke test failures.
Added environment variables to CI workflow:
- `OTEL_SKIP_COLLECTOR_CHECK=true` - Skip collector availability check
- `OTEL_RETRY_DURATION_MINS=0` - Disable retry attempts in CI
This allows the MCP agent to start immediately in CI without waiting for a collector.
Fixes the issue reported where smoke tests were failing after telemetry changes.
> fix: prevent telemetry from blocking CI smoke tests

- terminator-mcp-agent/tests/telemetry_tests.rs
Fixes CI test failures caused by telemetry tests waiting for OpenTelemetry collector.
The `test_telemetry_initialization` test was attempting to connect to an OpenTelemetry collector even though:
1. CI workflow had `OTEL_SKIP_COLLECTOR_CHECK=true` set at the top level
2. Tests spawn their own process context and don't inherit these env vars properly
3. This caused tests to wait up to 15 minutes for a collector that doesn't exist
Added environment variables directly in the test functions:
- `OTEL_SKIP_COLLECTOR_CHECK=true` - Skip collector availability check
- `OTEL_RETRY_DURATION_MINS=0` - Disable retry attempts
This ensures tests don't block waiting for a non-existent collector.
- Modified `test_telemetry_initialization()` to set skip env vars
- Modified `test_with_telemetry_enabled()` …
> fix: prevent telemetry tests from blocking in CI

- vagrant/README-VAGRANT.md
- vagrant/Vagrantfile-enhanced
- vagrant/scripts/extension-watcher.ps1
- vagrant/scripts/mcp-watcher.ps1
- Added hot reload capabilities for MCP server and browser extensions in Vagrant VM
- Enhanced Vagrant configuration with performance optimizations
- Comprehensive documentation for local development workflow
- **`mcp-watcher.ps1`**: Monitors MCP binary changes and auto-restarts the server
- **`extension-watcher.ps1`**: Watches browser extension files and triggers Chrome reloads
- Increased resources: 8GB RAM, 4 CPUs for better development performance
- Added VirtualBox optimizations (paravirt provider, nested paging, large pages)
- Port forwarding for MCP (8080) and Chrome debugging (9222)
- Pre-installed development tools: Rust, Chrome, Node.js, Python
- Scheduled tasks for automatic watcher startup
- Added comprehensive README-VAGRANT.md with setup and usage instructions
- Quick start …
> feat: add Vagrant hot reload support for MCP development

- terminator-mcp-agent/src/telemetry.rs
When the OpenTelemetry collector is unreachable, `execute_sequence` workflows would hang indefinitely waiting for telemetry export to complete. The OTLP exporter timeout was set to 10 seconds, and when `workflow_span.end()` was called at the end of `execute_sequence`, it would block waiting for the export to complete.
Individual tool calls (like `open_application`, `type_into_element`) don't create workflow spans, so they weren't affected. Only `execute_sequence` creates workflow spans that trigger this blocking behavior.
The issue is in `terminator-mcp-agent/src/telemetry.rs:314`:
```rust
.with_timeout(Duration::from_secs(10))
```
When the OTLP collector at the configured endpoint is unreachable, the exporter would wait up to 10 seconds trying to send data, blocking the entire HTTP …
> fix: Reduce OTLP exporter timeout to 500ms to prevent execute_sequence hanging
